#!/usr/bin/env python3

"""
Helper script for using Wizz Air API with browser-extracted headers and cookies.

Wizz Air uses bot protection (Kasada SDK + Akamai Bot Manager) that prevents
automated access. This script shows how to use headers and cookies extracted
from a real browser session.

IMPORTANT NOTES:
1. These headers/cookies expire quickly (usually within minutes to hours)
2. Using extracted headers may violate Wizz Air's Terms of Service
3. This is for educational purposes only
4. For production use, consider official API access or browser automation

How to extract headers and cookies:
====================================

1. Open Wizz Air website in Firefox/Chrome
2. Open Developer Tools (F12)
3. Go to Network tab
4. Search for a flight (to trigger API calls)
5. Find the POST request to "search/search"
6. Right-click → Copy → Copy as cURL
7. Extract the headers and cookies from the cURL command

Alternatively, in the Network tab:
1. Click on the "search/search" request
2. Go to Headers tab
3. Copy Request Headers manually
4. Go to Cookies tab and copy cookie values
"""

from wizz_air import WizzAirAPI


def example_with_extracted_headers():
    """
    Example of using WizzAirAPI with headers extracted from a browser.

    Replace the placeholder values with actual values from your browser session.
    """

    # Bot protection headers (extract from browser Developer Tools)
    bot_protection_headers = {
        # Anti-CSRF token - changes with each session
        'X-RequestVerificationToken': 'YOUR_TOKEN_HERE',

        # Kasada SDK headers - generated by JavaScript bot protection
        'x-kpsdk-ct': 'YOUR_KASADA_CT_HERE',
        'x-kpsdk-cd': 'YOUR_KASADA_CD_HERE',
        'x-kpsdk-v': 'j-1.1.29259',  # Version may change
        'x-kpsdk-h': 'YOUR_KASADA_HASH_HERE',
    }

    # Cookies (extract from browser)
    cookies = {
        # Must match X-RequestVerificationToken header
        'RequestVerificationToken': 'YOUR_TOKEN_HERE',

        # Akamai Bot Manager session cookie
        'ak_bm_vw_1.1': 'YOUR_AKAMAI_SESSION_HERE',
        'ak_bm_vw_1.1-ssn': 'YOUR_AKAMAI_SSN_HERE',

        # ASP.NET session
        'ASP.NET_SessionId': 'YOUR_SESSION_ID_HERE',

        # Other required cookies
        'OptanonConsent': 'YOUR_CONSENT_STRING_HERE',
        'OptanonAlertBoxClosed': '2025-07-18T12:11:14.508Z',
        'configCatBeId': 'YOUR_CONFIG_ID_HERE',
        'bv': '',
    }

    # Initialize API with extracted headers and cookies
    api = WizzAirAPI(
        custom_headers=bot_protection_headers,
        cookies=cookies
    )

    # Now you can use the API normally
    try:
        # Example: Get flight dates
        flight_dates = api.get_flight_dates(
            departure_station="WRO",
            arrival_station="NCE",
            from_date="2025-12-13",
            to_date="2026-01-13"
        )
        print(f"✓ Successfully fetched {len(flight_dates.flightDates)} flight dates")

        # Example: Search flights
        search_result = api.search_flights(
            departure_station="WRO",
            arrival_station="NCE",
            departure_date="2025-12-13T00:00:00",
            return_date="2025-12-20T00:00:00",
            adult_count=1
        )
        print(f"✓ Successfully fetched flights")
        print(f"  Outbound: {len(search_result.outboundFlights)}")
        print(f"  Return: {len(search_result.returnFlights)}")

    except Exception as e:
        print(f"✗ Request failed: {e}")
        print("\nPossible reasons:")
        print("1. Headers/cookies have expired (try extracting fresh ones)")
        print("2. Bot protection detected the request pattern")
        print("3. Network/connectivity issues")


def extract_from_curl_command():
    """
    Example of parsing headers from a cURL command copied from browser.

    In Developer Tools:
    1. Right-click on the request
    2. Copy → Copy as cURL
    3. Parse the cURL command to extract headers and cookies
    """
    # Example cURL command structure:
    curl_command = """
    curl 'https://be.wizzair.com/27.35.0/Api/search/search' \\
      -H 'X-RequestVerificationToken: abc123' \\
      -H 'Cookie: RequestVerificationToken=abc123; ak_bm_vw_1.1=xyz789' \\
      -H 'x-kpsdk-ct: ...' \\
      --data-raw '{"isFlightChange":false,...}'
    """

    print("To extract headers from cURL:")
    print("1. Copy the entire cURL command from browser DevTools")
    print("2. Parse -H flags to get headers")
    print("3. Parse Cookie header to get individual cookies")
    print("4. Use them to initialize WizzAirAPI")


def alternative_browser_automation():
    """
    Alternative approach: Use browser automation to bypass bot protection.

    This is more reliable but slower than direct API calls.
    """
    print("\nAlternative: Browser Automation")
    print("=" * 60)
    print("""
For a more reliable solution, consider using browser automation:

1. Selenium with undetected-chromedriver:
   - Runs a real Chrome browser
   - Bot protection JavaScript executes normally
   - Can extract cookies and make API calls from the same session

2. Playwright:
   - Similar to Selenium but more modern
   - Better handling of async operations
   - Can intercept network requests

Example with Selenium:
```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import undetected_chromedriver as uc

# Use undetected chromedriver to bypass bot detection
driver = uc.Chrome()

# Navigate to Wizz Air
driver.get('https://www.wizzair.com')

# Wait for bot protection to initialize
time.sleep(5)

# Extract cookies from the browser
cookies = driver.get_cookies()

# Now use these cookies with requests or continue using Selenium
```

This approach:
- ✓ Bypasses bot protection naturally
- ✓ More reliable
- ✗ Slower (full browser overhead)
- ✗ Requires browser drivers
""")


if __name__ == "__main__":
    print("Wizz Air API with Bot Protection Bypass")
    print("=" * 60)
    print()
    print("⚠️  WARNING: This is for educational purposes only!")
    print("⚠️  Using extracted headers may violate Terms of Service")
    print()
    print("=" * 60)
    print()

    print("Method 1: Manual Header Extraction")
    print("-" * 60)
    print(__doc__)

    print("\nMethod 2: Browser Automation (Recommended)")
    print("-" * 60)
    alternative_browser_automation()

    print("\n" + "=" * 60)
    print("To test with real headers:")
    print("1. Extract headers from browser DevTools")
    print("2. Update the example_with_extracted_headers() function")
    print("3. Run this script")
    print("=" * 60)
